#!/usr/bin/env python
#
# Cleans a Cocos2d-x project.
#
# @copyright 2015 Upstart Illustration LLC. All rights reserved.
#

from subprocess import call

import os

from ugf import gethomedir
from ugf.config import Config
from ugf.pathbuilder import CocosPathBuilder

def main(cocos):
    os.chdir(cocos.basepath())
    return
    # Removes all untracked files
    call(["git", "clean", "-f", "-d"])
    # Removes all unstaged files
    call(["git", "checkout", "."])

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Upstart Game Framework - Clean a Cocos2d-x project")
    parser.add_argument('version', help="The version of cocos to clean. Version must be in the format of #.#.# (e.g. 1.0.4)")
    args = parser.parse_args()

    config = Config.load(os.path.join(gethomedir(), ".ugf"))
    cocos = CocosPathBuilder(config, args.version)
    main(cocos)
